# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/security/R-cran-digest/Makefile 419604 2016-08-04 09:33:27Z tota $

PORTNAME=	digest
PORTVERSION=	0.6.10
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
