#!/bin/sh

echo "$0 $*"

args="$*"

while [ $# -gt 0 ]
do
    arg="$1"; shift
    case "$arg" in
        */project.json)
            project_json="$arg"
            ;;
    esac
done

if [ -z "$project_json" ]
then
    echo "err: no project file specified" >&2
    exit 1
fi

WRKSRC="/home/dbn/ports/ports/devel/msbuild/work/linux-packaging-msbuild-431c7ec"

project_lock_json="`dirname "$project_json" | sed "s|$WRKSRC/||"`/project.lock.json"

if [ ! -f "$project_lock_json" ]
then
  sed -e "s|C:\\\\Users\\\\dnaylor\\\\.nuget\\\\packages|$NUGET_PACKAGEDIR|" /home/dbn/archive/work/Deloitte/dnaylor/dotnet/msbuild/$project_lock_json > "$WRKSRC/$project_lock_json"
fi
