# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/pypy-setuptools33/Makefile 352367 2014-04-26 19:31:10Z sunpoet $

PKGNAMESUFFIX=	${PYTHON_SUFFIX}

PYTHON_VERSION=	pypy3.3

MASTERDIR=	${.CURDIR}/../py-setuptools

.include "${MASTERDIR}/Makefile"
