# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	lttng-ust
PORTVERSION=	2.4.1
CATEGORIES=	sysutils linux
MASTER_SITES=	EPEL7/l

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Libraries to instrument and trace user applications CentOS ${LINUX_DIST_VER})

ONLY_FOR_ARCHS=	amd64
DESCR=		${PORTSDIR}/sysutils/lttng-ust/pkg-descr
RPMVERSION=	4.el7
USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

.include <bsd.port.mk>
