# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-memoise/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	memoise
PORTVERSION=	1.0.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Memoise functions for R

LICENSE=	MIT

RUN_DEPENDS=	R-cran-digest>=0.6.3:security/R-cran-digest

USES=	cran:auto-plist

.include <bsd.port.mk>
