# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-zoo/Makefile 414589 2016-05-04 07:18:27Z tota $

PORTNAME=	zoo
DISTVERSION=	1.7-13
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	S3 Infrastructure for Regular and Irregular Time Series

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
