# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-deldir/Makefile 410683 2016-03-09 02:42:31Z tota $

PORTNAME=	deldir
DISTVERSION=	0.1-12
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Delaunay Triangulation and Dirichlet (Voronoi) Tessellation

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
