# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/graphics/R-cran-colorspace/Makefile 424038 2016-10-16 04:18:26Z tota $

PORTNAME=	colorspace
DISTVERSION=	1.2-7
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
