# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libicu
PORTVERSION=	50.1.2
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Generic stack unwinding library (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${PORTSDIR}/devel/icu/pkg-descr
RPMVERSION=	15.el7
USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes
SRC_DISTFILES=	

.include <bsd.port.mk>
