# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-setuptools35/Makefile 396880 2015-09-14 04:36:05Z koobs $

PKGNAMESUFFIX=	${PYTHON_SUFFIX}

PYTHON_VERSION=	cpython3.5

MASTERDIR=	${.CURDIR}/../py-setuptools

.include "${MASTERDIR}/Makefile"
