# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/devel/R-cran-reshape/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	reshape
PORTVERSION=	0.8.5
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R package for flexibly restructuring and aggregating data

LICENSE=	MIT

RUN_DEPENDS=	R-cran-plyr>0:devel/R-cran-plyr

USES=	cran:auto-plist

.include <bsd.port.mk>
