# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-KFAS/Makefile 429317 2016-12-24 09:12:10Z tota $

PORTNAME=	KFAS
PORTVERSION=	1.2.5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Kalman filter and smoothers for exponential family state space models

LICENSE=	GPLv2+

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
