# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-KFAS/Makefile 419301 2016-07-30 08:15:11Z tota $

PORTNAME=	KFAS
PORTVERSION=	1.2.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Kalman filter and smoothers for exponential family state space models

LICENSE=	GPLv2+

USES=	cran:auto-plist,fortran

.include <bsd.port.mk>
