# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-KFAS/Makefile 428057 2016-12-07 13:24:56Z gerald $

PORTNAME=	KFAS
PORTVERSION=	1.2.4
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Kalman filter and smoothers for exponential family state space models

LICENSE=	GPLv2+

USES=	cran:auto-plist,fortran

.include <bsd.port.mk>
