# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/textproc/R-cran-R2HTML/Makefile 417531 2016-06-26 15:17:31Z thierry $

PORTNAME=	R2HTML
PORTVERSION=	2.3.2
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	HTML exportation for R objects

LICENSE=	GPLv2

USES=		cran
NO_ARCH=	yes

.include <bsd.port.mk>
