# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-XML/Makefile 427762 2016-12-04 09:03:02Z tota $

PORTNAME=	XML
DISTVERSION=	3.98-1.5
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD2CLAUSE

USES=	cran:auto-plist,compiles
USE_GNOME=	libxml2

.include <bsd.port.mk>
