# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/textproc/R-cran-XML/Makefile 409995 2016-03-03 01:20:46Z tota $

PORTNAME=	XML
DISTVERSION=	3.98-1.4
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD2CLAUSE

USES=	cran:auto-plist
USE_GNOME=	libxml2

.include <bsd.port.mk>
