# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD$

PORTNAME=	dotnet10-sdk
DISTVERSION=	1.0.4
DISTNAME=	dotnet-dev-centos-x64.${DISTVERSION}
MASTER_SITES=	https://download.microsoft.com/download/E/7/8/E782433E-7737-4E6C-BFBF-290A0A81C3D7/

RUN_DEPENDS=	linux-dotnet10-runtime>=0:lang/linux-dotnet10-runtime

EXTRACT_EXTRA_ARGS=

MASTERDIR=	${.CURDIR}/../linux-dotnet-sdk

.include "${MASTERDIR}/Makefile"
