# $FreeBSD: head/editors/libreoffice/Makefile.common 426069 2016-11-13 22:38:15Z bapt $

PORTNAME=	libreoffice
PORTVERSION=	5.2.3
PORTREVISION=	2
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		3
