# $FreeBSD: head/editors/libreoffice/Makefile.common 423591 2016-10-09 12:10:02Z jbeich $

PORTNAME=	libreoffice
PORTVERSION=	5.0.6
PORTREVISION=	4
CATEGORIES+=	editors
 
MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		3
