# $FreeBSD: head/editors/libreoffice/Makefile.common 427743 2016-12-03 22:24:36Z jbeich $

PORTNAME=	libreoffice
PORTVERSION=	5.2.3
PORTREVISION=	5
CATEGORIES+=	editors

MAINTAINER=	office@FreeBSD.org

LICENSE=	LGPL3+ MPL
LICENSE_COMB=	dual

LOVERSION=	${PORTVERSION}.${RCVER}
RCVER=		3
