# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD: head/devel/py-typed-ast/Makefile 432468 2017-01-26 06:18:29Z dbn $

PORTNAME=	typed-ast
PORTVERSION=	0.6.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Fast version of Python's ast module with support for PEP484 typed comments

LICENSE=	APACHE20 PSFL
LICENSE_COMB=	multi
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.3+
USE_PYTHON=	autoplist distutils concurrent

.include <bsd.port.mk>
