# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD: head/math/R-cran-gss/Makefile 421103 2016-08-30 05:56:02Z dbn $

PORTNAME=	gss
DISTVERSION=	2.1-6
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	General Smoothing Splines

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
