# Created by: David Naylor <dbn@FreeBSD.org>
# $FreeBSD: head/x11-themes/kde4-style-oxygen-transparent/Makefile 420774 2016-08-24 08:20:31Z tcberner $

PORTNAME=	oxygen-transparent
PORTVERSION=	2014.03.10
PORTREVISION=	2
CATEGORIES=	x11-themes kde
MASTER_SITES=	LOCAL/dbn/${PORTNAME}
PKGNAMEPREFIX=	kde4-style-

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	KDE oxygen style with transparency

LICENSE=	GPLv2

USES=		cmake kde:4 tar:xz
USE_KDE=	kdelibs workspace automoc4
USE_QT4=	corelib qmake_build moc_build rcc_build uic_build

.include <bsd.port.mk>
