# Created by: Piotr Kubaj <pkubaj@anongoth.pl>
# $FreeBSD$

PORTNAME=	libicu
PORTVERSION=	4.2.1
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Generic stack unwinding library (Linux CentOS ${LINUX_DIST_VER})

DESCR=		${PORTSDIR}/devel/icu/pkg-descr
RPMVERSION=	14.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes
SRC_DISTFILES=

.include <bsd.port.mk>
