# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: head/math/R-cran-memisc/Makefile 418863 2016-07-21 04:55:25Z tota $

PORTNAME=	memisc
DISTVERSION=	0.99.7-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides an infrastructure for the management of survey data

LICENSE=	GPLv2

USES=	cran:auto-plist,compiles

.include <bsd.port.mk>
