# $FreeBSD: head/graphics/R-cran-scales/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	scales
PORTVERSION=	0.4.0
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Scale functions for graphics

LICENSE=	MIT

RUN_DEPENDS=	R-cran-RColorBrewer>0:graphics/R-cran-RColorBrewer \
		R-cran-dichromat>0:graphics/R-cran-dichromat \
		R-cran-plyr>0:devel/R-cran-plyr \
		R-cran-munsell>=0.2:graphics/R-cran-munsell \
		R-cran-labeling>0:math/R-cran-labeling \
		R-cran-Rcpp>0:devel/R-cran-Rcpp

USES=	cran:auto-plist

.include <bsd.port.mk>
